version: '3.8'

services:
  # Development service
  dev:
    build: 
      context: .
      target: builder
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev
    environment:
      - NODE_ENV=development

  # Production service
  prod:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production 